name = "RandomizedPropertyTest"
uuid = "6d7a0864-9fbc-11e9-1427-7bb65d6eba8e"
authors = ["Lukas Himbert <lukas_himbert@posteo.de>"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
